2024-02-01 13:01:03 : DEBUG : <module> : 439 : --- Start ---
2024-02-01 13:01:03 : DEBUG : load_ui : 405 : - Load UI -
2024-02-01 13:01:03 : ERROR : <module> : 447 : Failed
2024-02-01 13:01:03 : ERROR : <module> : 448 : No section: 'tkinter'
Traceback (most recent call last):
  File "c:\Users\user\Documents\shifter-python\prueba.py", line 444, in <module>
    load_ui()
  File "c:\Users\user\Documents\shifter-python\prueba.py", line 410, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2024-02-01 13:01:03 : DEBUG : <module> : 451 : --- End ---
